# Generated by Django 5.0.4 on 2024-04-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attemps',
            field=models.IntegerField(default=0),
        ),
    ]
