# Generated by Django 5.0.4 on 2024-04-21 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
